# Generated by Django 5.2 on 2025-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona_protetyczna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cennikpozycja',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
